# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ASP.NET Core and React Blog
description: > # this means to ignore newlines until "baseurl:"
  This website is a dedicate blog to the ASP.NET Core and React book published by Packt Publishing. 
  You will find information about these two web technologies and ways to successfully 
  implement solutions using them. As the author of the book, I thank you for visiting the site and please send 
  me a note if you have any questions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: navarrorc
github_username:  navarrorc

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - node_modules
